# DISA STIG:
#   SRG-NET-000230-RTR-000001
#   Severity: medium
#   Rule ID: SV-221073r999681
#   Identifiers: SV-110963, V-101859, CCI-000366, CCI-002205
#   Title: The Cisco switch must be configured to implement message authentication for all control plane protocols.
---
# STIG Rule: SV-221072r999681 - Ensure message authentication for control plane protocols

- name: "[SV-221072r999681] Gather running config"
  cisco.nxos.nxos_command:
    commands:
      - show running-config
  register: running_config

- name: "[SV-221072r999681] Set facts for active protocols"
  set_fact:
    has_ospf: "{{ 'router ospf' in running_config.stdout[0] }}"
    has_eigrp: "{{ 'router eigrp' in running_config.stdout[0] }}"
    has_isis: "{{ 'router isis' in running_config.stdout[0] }}"
    has_rip: "{{ 'router rip' in running_config.stdout[0] }}"
    has_bgp: "{{ 'router bgp' in running_config.stdout[0] }}"

- name: "[SV-221072r999681] Get interfaces from running config"
  set_fact:
    protocol_interfaces: >-
      {{
        running_config.stdout[0].split('\n')
        | select('match', '^interface')
        | map('regex_replace', '^interface ', '')
        | list
      }}

# === OSPF ===
- name: "[SV-221072r999681] Configure OSPF interface authentication"
  cisco.nxos.nxos_config:
    lines:
      - ip ospf authentication
      - ip ospf authentication key-chain {{ ospf_key_chain }}
    parents: interface {{ item }}
  loop: "{{ protocol_interfaces }}"
  when: has_ospf and ospf_key_chain is defined

# === EIGRP ===
- name: "[SV-221072r999681] Configure EIGRP interface authentication"
  cisco.nxos.nxos_config:
    lines:
      - ip authentication mode eigrp 1 md5
      - ip authentication key-chain eigrp 1 {{ eigrp_key_chain }}
    parents: interface {{ item }}
  loop: "{{ protocol_interfaces }}"
  when: has_eigrp and eigrp_key_chain is defined

# === IS-IS ===
- name: "[SV-221072r999681] Configure IS-IS interface authentication"
  cisco.nxos.nxos_config:
    lines:
      - isis authentication-type md5 level-1
      - isis authentication key-chain {{ isis_key_chain }} level-1
    parents: interface {{ item }}
  loop: "{{ protocol_interfaces }}"
  when: has_isis and isis_key_chain is defined

# === RIP ===
- name: "[SV-221072r999681] Configure RIP interface authentication"
  cisco.nxos.nxos_config:
    lines:
      - ip rip authentication mode md5
      - ip rip authentication key-chain {{ rip_key_chain }}
    parents: interface {{ item }}
  loop: "{{ protocol_interfaces }}"
  when: has_rip and rip_key_chain is defined

# === BGP ===
- name: "[SV-221072r999681] Configure BGP neighbor password"
  cisco.nxos.nxos_config:
    lines:
      - neighbor {{ item }} password {{ bgp_password }}
    parents:
      - router bgp {{ bgp_as }}
  loop: "{{ bgp_neighbors }}"
  when: has_bgp and bgp_as is defined and bgp_password is defined and bgp_neighbors is defined


